### ISSUE TITLE
Support for modifying JVM arguments when forking findbugs

### ISSUE THREAD

**Issue by stephenc** [mojohaus/findbugs-maven-plugin-old#2]
In general, when running on e.g. a Mac, it is preferred to run Maven with `-Djava.awt.headless=true` in your MAVEN_OPTS so that forked JVMs do not steal focus.

When running the `findbugs:gui` goal, however, you get the following unintuitive error message:

```
$ MAVEN_OPTS="$MAVEN_OPTS -Djava.awt.headless=true" mvn findbugs:gui
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building _________ _________-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- findbugs-maven-plugin:3.0.1:gui (default-cli) @ _________ ---
[INFO] File Encoding is UTF-8
     [java] The following errors occurred during analysis:
     [java]   Cannot open codebase filesystem:/Users/stephenc/src/_________/target/findbugsXml.xml
     [java]     java.io.IOException: Wrong magic bytes of a3c4275 for zip file /Users/stephenc/src/_________/target/findbugsXml.xml of 134745 bytes
     [java]       At edu.umd.cs.findbugs.classfile.impl.ZipFileCodeBase.<init>(ZipFileCodeBase.java:87)
     [java]       At edu.umd.cs.findbugs.classfile.impl.ZipCodeBaseFactory.makeZipCodeBase(ZipCodeBaseFactory.java:39)
     [java]       At edu.umd.cs.findbugs.classfile.impl.ClassFactory.createFilesystemCodeBase(ClassFactory.java:121)
     [java]       At edu.umd.cs.findbugs.classfile.impl.FilesystemCodeBaseLocator.openCodeBase(FilesystemCodeBaseLocator.java:77)
     [java]       At edu.umd.cs.findbugs.classfile.impl.ClassPathBuilder.processWorkList(ClassPathBuilder.java:607)
     [java]       At edu.umd.cs.findbugs.classfile.impl.ClassPathBuilder.build(ClassPathBuilder.java:226)
     [java]       At edu.umd.cs.findbugs.FindBugs2.buildClassPath(FindBugs2.java:677)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:218)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
     [java]       At edu.umd.cs.findbugs.LaunchAppropriateUI.launch(LaunchAppropriateUI.java:106)
     [java]       At edu.umd.cs.findbugs.LaunchAppropriateUI.main(LaunchAppropriateUI.java:198)
     [java] Exception in thread "main" java.io.IOException: No files to analyze could be opened
     [java]     at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:276)
     [java]     at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
     [java]     at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
     [java]     at edu.umd.cs.findbugs.LaunchAppropriateUI.launch(LaunchAppropriateUI.java:106)
     [java]     at edu.umd.cs.findbugs.LaunchAppropriateUI.main(LaunchAppropriateUI.java:198)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.538 s
[INFO] Finished at: 2015-07-24T12:25:53+01:00
[INFO] Final Memory: 29M/347M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:findbugs-maven-plugin:3.0.1:gui (default-cli) on project _________: Execution default-cli of goal org.codehaus.mojo:findbugs-maven-plugin:3.0.1:gui failed: Java returned: 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

The error goes away if you turn headless off.

What I would really like is the ability to control the jvm args for the fork **of the fundbugs:gui goal** independently from findbugs in general.

That way I can have

`MAVEN_OPTS=-Djava.awt.headless=true -Dfindbugs.jvmArgs=-Djava.awt.headless=true -Dfindbugs.guiJvmArgs=-Djava.awt.headless=false`

Then running `mvn verify` will not steal my focus and when I need to see the findbugs issues I can run `mvn findbugs:gui` and get the GUI

**Comment by VsevolodGolovanov** [comment]
Couldn't you just do

```
<execution>
    <id>default-cli</id>
    <goals>
        <goal>gui</goal>
    </goals>
    <configuration>
        <jvmArgs>-Djava.awt.headless=false</jvmArgs>
    </configuration>
</execution>
```

Alternatively create a maven profile.

**Comment by stephenc** [comment]
That will not let one do `mvn verify findbugs:gui` and only have focus stolen if/when the gui launches. 

Modifying a profile means I have to modify the Pom of the project I checked out. Often times I'm working on any one of 1000 random projects so it gets annoying if you have to remember to "fix" every one of them... Plus then I need to remember not to add those changes into the PR as often times the repo maintainer doesn't want those kind of Pom changes

**Comment by stephenc** [comment]
abandoned plugin. closing issue as stale
